name: Smoke Tests

on:
  push:
  pull_request:

jobs:
  minimal-smoke:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Try restore with uv (fallback to pip on failure)
        run: |
          set -e
          if command -v uv >/dev/null 2>&1; then
            echo "Running uv to install dependencies from uv.lock"
            uv install || (
              echo "uv install failed, falling back to pip install of test deps";
              python -m pip install pytest numpy scikit-learn tomli tomli-w
            )
          else
            echo "uv not found after pip install; falling back to pip install of test deps"
            python -m pip install pytest numpy scikit-learn tomli tomli-w
          fi
      - name: Run pytest
        run: |
          pytest -q